### ISSUE TITLE
Clean backup files after tests run

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/testfm#143]
Recent automation made system memory usage 100%. To resolve issue, clean backup files after tests run.

**Comment by jyejare** [comment]
IMHO, 

- Cleanup should be handled in TearDown
- Handle exceptions in TearDown so that it will erase what it should, even though there is an exception in TearDown.
- When one interrupts manual test execution (instead of CI) on jenkins nodes , make sure the cleanup is done manually.
