### ISSUE TITLE
Add scenarios to test version-locking feature of FM

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/testfm#69]
upstream PR: [https://github.com/theforeman/foreman_maintain/pull/249](https://github.com/theforeman/foreman_maintain/pull/249)
upstream issue: [https://projects.theforeman.org/issues/26216](https://projects.theforeman.org/issues/26216)

Scenarios to test in Testfm:

- [ ]  satellite-installer --lock-package-versions 
     - Check packages are locked or not using: 
          - foreman-maintain packages is-locked
          - foreman-maintain packages status
          - Check using yum command 
          - Check locked packages listed in file
     - Run satellite-installer --no-lock-package-versions
          - Check packages are unlocked or not using:
               - foreman-maintain packages is-locked
               - foreman-maintain packages status
               - Check using yum command
               - Check packages are not listed in file anymore

- [ ] foreman-maintain packages lock
     - Check packages are locked or not using: 
          - foreman-maintain packages is-locked
          - foreman-maintain packages status
          - Check using yum command 
          - Check locked packages listed in file
     - Run foreman-maintain packages unlock
          - Check packages are unlocked or not using:
               - foreman-maintain packages is-locked
               - foreman-maintain packages status
               - Check using yum command
               - Check packages are not listed in file anymore

**Comment by jameerpathan111** [comment]
PR #70 need to be changed to find the expected number of packages to be locked, (Only If it's feasible and won't complicate the test) otherwise remove the assertion which checks number of packages which got locked with total number of packages which a satellite/foreman repo provides.

**Comment by jameerpathan111** [comment]
> PR #70 need to be changed to find the expected number of packages to be locked, (Only If it's feasible and won't complicate the test) otherwise remove the assertion which checks number of packages which got locked with total number of packages which a satellite/foreman repo provides.

@ntkathole what do you think? is it worth doing?

**Comment by ntkathole** [comment]
@jameerpathan111 simple approach can be get of packages such as satellite-installer/satellite/foreman/katello in satellite and check those are locked.

**Comment by jameerpathan111** [comment]
> PR #70 need to be changed to find the expected number of packages to be locked, (Only If it's feasible and won't complicate the test) otherwise remove the assertion which checks number of packages which got locked with total number of packages which a satellite/foreman repo provides.

Solution: 
- no. of installed packages from foreman/Satellite repo `yum list installed | grep @Sat_repo_id | wc -l`
- or use `repoquery -a --installed '| grep 'sat_repo_id | wc -l `
- compare with total no. of packages provided by sat_repo

**Comment by jameerpathan111** [comment]
Refs #100 and #96
