### ISSUE TITLE
Fix tests related to check for old tasks in paused/stopped state.

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/testfm#98]
Currently this check runs on Satellite having no old tasks in paused/stopped.

**Comment by jameerpathan111** [comment]
Refs FM PR: [https://github.com/theforeman/foreman_maintain/pull/279](https://github.com/theforeman/foreman_maintain/pull/279)

**Comment by ntkathole** [comment]
Consider this for adding coverage around https://bugzilla.redhat.com/show_bug.cgi?id=1745489
